services:

  - type: web

    name: binalvision-server

    env: node

    rootDir: server

    buildCommand: npm install

    startCommand: npx tsx index.ts

    envVars:

      - key: NODE_ENV

        value: production
 
  - type: static

    name: binalvision-client

    rootDir: client

    buildCommand: npm install && npm run build

    staticPublishPath: dist
 
